[package]
name = "philoch_bib_sdk"
version = "0.1.6"
edition = "2021"

[lib]
name = "_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
ahash = "0.8"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
